### ISSUE TITLE
Protect branches

### ISSUE THREAD

**Issue by anderslogg** [dtcc-platform/dtcc-model#1]

**Comment by vbassn** [comment]
@anderslogg let's decide on which boxes to tick!

https://github.com/dtcc-platform/dtcc-model/settings/branch_protection_rules/new?branch_name=main

**Comment by anderslogg** [comment]
@vbassn Perhaps just the top one (require pull request)? Let's start simple.

**Comment by vbassn** [comment]
I ve added the first two and need 2 approvals (for now)
