### ISSUE TITLE
Method to return a 3D bounds for a Mesh object

### ISSUE THREAD

**Issue by snjsomnath** [dtcc-platform/dtcc-model#25]
https://github.com/dtcc-platform/dtcc-model/blob/6516b992416964cf33052d9831af107e76b16dfb/src/dtcc_model/geometry/mesh.py#L109

The Mesh.center() returns the geometric center of the points. It would also be useful to do something like Mesh.bounds() / Mesh.bbox or something similar to return a 3D bounding box which could then have a its own center method.

This is useful for transform operations, for example in the Unreal workflow.

**Comment by anderslogg** [comment]
@snjsomnath @dwastberg Agree. We already have that in the new data model (which is half-implemented). A Mesh is a subclass of Geometry and Geometry has a .bounds member which has .center.

**Comment by anderslogg** [comment]
I think this is fixed. A ``Mesh`` is a ``Geometry`` and therefore has ``.bounds``
